libcstr: cstr.h File Reference
cstr.h File Reference
cstr header file
Data Structures
struct cstr
The cstr_t data type.
Defines
#define MIN(X, Y) (X < Y ? X : Y)
#define CSTR_NICE_FREE(X) free(X); X=NULL
#define CSTR_INIT_SIZE 63
#define CSTR_SIZE(X) ((X)->size)
#define CSTR_LEN(X) ((X)->len)
#define CSTR_STR(X) ((X)->str)
Typedefs
typedef struct cstr * cstr_t
The cstr_t data type.
Enumerations
enum CASE { UPPER, LOWER, SWAP }
Case change choice enum.
Functions
unsigned long int powerup (unsigned long int n)
Get the next power of 2.
cstr_t cstrInit (void)
Create a cstr_t instance.
cstr_t cstrInit2 (unsigned long int n)
Create a cstr_t instance defining the buffer size.
cstr_t cstrInitChar (char *s)
Create and initialize a cstr_t instance.
void cstrDel (cstr_t str)
Destroy a cstr_t instance.
unsigned long int cstrLength (cstr_t str)
Get string length.
unsigned long int cstrSize (cstr_t str)
Get buffer size.
const char * cstrGetChar (cstr_t str)
Get a pointer to the string.
void cstrResize (cstr_t str)
Re-calculate minimum buffer size.
int cstrUpdate (cstr_t str, const char *s)
Store a new string in a cstr instance.
int cstrUpdateFormat (cstr_t str, char *fmt,...)
Store a new string in a cstr instance according to a format.
int cstrCharAt (cstr_t str, unsigned long int i)
Get the i-th character.
unsigned long int cstrIndexOf (cstr_t str, char c)
Get the (first) index of a character.
unsigned long int cstrLastIndexOf (cstr_t str, char c)
Get the (last) index of a character.
int cstrEquals (cstr_t str1, cstr_t str2)
String comparison.
int cstrEqualsI (cstr_t str1, cstr_t str2)
String comparison (case insensitive).
int cstrIsClone (cstr_t str1, cstr_t str2)
cstr instance comparison
unsigned long int cstrConcat (cstr_t dst, cstr_t str1, cstr_t str2)
String concatenation.
unsigned long int cstrConcatInPlace (cstr_t str1, cstr_t str2)
String concatenation (in place).
unsigned long int cstrConcatInPlaceChar (cstr_t str1, char *str2)
String concatenation (in place).
unsigned long int cstrConcatMany (cstr_t str,...)
Concatenate lots of strings.
void cstrCopy (cstr_t str1, cstr_t str2)
String copy.
void cstrReverse (cstr_t str)
String reverse.
void cstrMakeSingleSpace (cstr_t str)
Remove extra space.
void cstrLower (cstr_t str)
Make the string lowercase.
void cstrUpper (cstr_t str)
Make the string uppercase.
void cstrCapitalize (cstr_t str)
Capitalize the string.
void cstrSwapCase (cstr_t str)
Switch upper with lower case and vice-versa.
void cstrStripL (cstr_t str)
Remove white space from the beginning of the string.
void cstrStripR (cstr_t str)
Remove white space from the end of the string.
void cstrStrip (cstr_t str)
Remove white space from both the beginning and the end of the string.
void cstrImport (cstr_t str, FILE *fp)
Import from file.
size_t cstrDump (cstr_t str, FILE *fp)
Write to file.
size_t cstrDumpN (cstr_t str, FILE *fp, unsigned long int n)
Write n characters to file.
void cstrImportN (cstr_t str, FILE *fp, unsigned long int n)
Read n characters from file.
void cstrImportCharN (cstr_t str, const char *buffer, unsigned long int n)
Read n characters from a byte sequence.
int cstrGetSubstring (cstr_t dst, cstr_t str, unsigned long int a, unsigned long int b)
Get a substring.
int cstrLeft (cstr_t dst, cstr_t str, unsigned long int i)
Get a substring starting at the beginning.
int cstrRight (cstr_t dst, cstr_t str, unsigned long int i)
Get a substring starting at the end.
unsigned long int cstrSearch (cstr_t str, char *s)
Search for a substring.
int cstrReplace (cstr_t str, const char *s1, const char *s2)
Replace a substring with another.
unsigned long int cstrReplaceAll (cstr_t str, const char *s1, const char *s2)
Replace all occurences of a substring with another.
void cstrDecodeURL (cstr_t str1, cstr_t str2)
Decode an encoded URL.
void cstrDecodeURLInPlace (cstr_t str)
Decode an encoded URL (in place).
Detailed Description
cstr header file
Define Documentation
#define CSTR_INIT_SIZE 63
default string size
Referenced by cstrImport(), cstrImportN(), and cstrInit().
#define CSTR_LEN (X) ((X)->len)
struct cstr string length field
Referenced by cstrCharAt(), cstrConcat(), cstrConcatInPlaceChar(), cstrConcatMany(), cstrDump(), cstrEqualsI(), cstrGetSubstring(), cstrImportCharN(), cstrIndexOf(), cstrInit2(), cstrIsClone(), cstrLastIndexOf(), cstrLength(), cstrMakeSingleSpace(), cstrReplaceAll(), cstrResize(), cstrReverse(), cstrRight(), cstrSearch(), cstrStripL(), cstrStripR(), cstrUpdate(), and cstrUpdateFormat().
#define CSTR_NICE_FREE (X) free(X); X=NULL
safe free(). makes the pointer NULL
Referenced by cstrDel(), cstrReplaceAll(), and cstrSearch().
#define CSTR_SIZE (X) ((X)->size)
struct cstr buffer size field
Referenced by cstrConcat(), cstrConcatInPlaceChar(), cstrInit2(), cstrIsClone(), cstrResize(), cstrSize(), and cstrUpdate().
#define CSTR_STR (X) ((X)->str)
struct cstr string buffer field
Referenced by cstrCapitalize(), cstrCharAt(), cstrConcat(), cstrConcatInPlace(), cstrConcatInPlaceChar(), cstrConcatMany(), cstrCopy(), cstrDecodeURLInPlace(), cstrDel(), cstrDump(), cstrDumpN(), cstrEquals(), cstrEqualsI(), cstrGetChar(), cstrGetSubstring(), cstrImportCharN(), cstrIndexOf(), cstrInit2(), cstrLastIndexOf(), cstrMakeSingleSpace(), cstrReplaceAll(), cstrResize(), cstrReverse(), cstrSearch(), cstrStripL(), cstrStripR(), cstrUpdate(), and cstrUpdateFormat().
#define MIN (X, Y) (X < Y ? X : Y)
simple, obvious minimum between two integers
Typedef Documentation
typedef struct cstr * cstr_t
The cstr_t data type.
Enumeration Type Documentation
enum CASE
Case change choice enum.
Function Documentation
void cstrCapitalize (cstr_t str)
Capitalize the string.
This function makes the first character after a sequence of white space upper case
Parameters:
str cstr_t instance
References CSTR_STR, and cstrCapitalize().
Referenced by cstrCapitalize().
int cstrCharAt (cstr_t str, unsigned long int i)
Get the i-th character.
This function returns the character at the position i of the stored string
The first position is 0
Parameters:
str cstr_t instance
i the index
Returns:
the i-th character or EOF if limits are exceeded
References CSTR_LEN, CSTR_STR, and cstrCharAt().
Referenced by cstrCharAt().
unsigned long int cstrConcat (cstr_t dst, cstr_t str1, cstr_t str2)
String concatenation.
This function concatenates str1 with str2 and puts the result in str
The buffer size of str will be increased if necessary
Parameters:
dst cstr_t instance which will hold the result of the concatenation
str1 cstr_t instance
str2 cstr_t instance
Returns:
the length of str or 0 if the buffer could not be increased
References CSTR_LEN, CSTR_SIZE, CSTR_STR, and cstrConcat().
Referenced by cstrConcat().
unsigned long int cstrConcatInPlace (cstr_t str1, cstr_t str2)
String concatenation (in place).
This function concatenates str1 with str2 and keeps the result in str1
The buffer size of str1 will be increased if necessary
Parameters:
str1 cstr_t instance
str2 cstr_t instance
Returns:
the new length of str1 or 0 if the buffer could not be increased
References CSTR_STR, cstrConcatInPlace(), and cstrConcatInPlaceChar().
Referenced by cstrConcatInPlace(), and cstrUpdateFormat().
unsigned long int cstrConcatInPlaceChar (cstr_t str1, char * str2)
String concatenation (in place).
Same as cstrConcatInPlace() but taking a char* as second argument
Parameters:
str1 cstr_t instance
str2 char* to be appended to the string stored int str1
Returns:
the new length of str1 or 0 if the buffer could not be increased
References CSTR_LEN, CSTR_SIZE, CSTR_STR, and cstrConcatInPlaceChar().
Referenced by cstrConcatInPlace(), cstrConcatInPlaceChar(), cstrConcatMany(), cstrImport(), cstrImportN(), and cstrUpdateFormat().
unsigned long int cstrConcatMany (cstr_t str, ...)
Concatenate lots of strings.
This function concatenates all the strings given as argument and places the result in the first argument, str. The strings which are to be concatenated have to be of type char*
The last argument must be NULL
Parameters:
str cstr_t instance which will hold the result
... lots of char* to be concatenated. The last one must be NULL!!
Returns:
the new length of str or 0 if the buffer could not be increased
References CSTR_LEN, CSTR_STR, cstrConcatInPlaceChar(), and cstrConcatMany().
Referenced by cstrConcatMany().
void cstrCopy (cstr_t str1, cstr_t str2)
String copy.
This function places a copy of str2 in str1. The buffer size of str1 will be increased if necessary.
Parameters:
str1 cstr_t instance
str2 cstr_t instance
References CSTR_STR, cstrCopy(), and cstrUpdate().
Referenced by cstrCopy(), and cstrDecodeURL().
void cstrDecodeURL (cstr_t str1, cstr_t str2)
Decode an encoded URL.
This function decodes the URL in str2 and saves the result in str1 The buffer size will be increased if necessary
Parameters:
str1 cstr_t instance with the result
str2 cstr_t instance with an encoded URL
References cstrCopy(), cstrDecodeURL(), and cstrDecodeURLInPlace().
Referenced by cstrDecodeURL().
void cstrDecodeURLInPlace (cstr_t str)
Decode an encoded URL (in place).
This function decodes the URL in str The buffer size will be increased if necessary
Parameters:
str cstr_t instance with an encoded URL
References CSTR_STR, and cstrDecodeURLInPlace().
Referenced by cstrDecodeURL(), and cstrDecodeURLInPlace().
void cstrDel (cstr_t str)
Destroy a cstr_t instance.
Destroy and free all allocated memory used by str
Parameters:
str cstr_t instance to be freed
References CSTR_NICE_FREE, CSTR_STR, and cstrDel().
Referenced by cstrDel().
size_t cstrDump (cstr_t str, FILE * fp)
Write to file.
This function writes the entire string to fp
Parameters:
str cstr_t instance
fp output destination
Returns:
the number of items successfully read or written not the number of characters
References CSTR_LEN, CSTR_STR, and cstrDump().
Referenced by cstrDump().
size_t cstrDumpN (cstr_t str, FILE * fp, unsigned long int n)
Write n characters to file.
This function writes the first n characters of the string to fp
Parameters:
str cstr_t instance
fp output destination
n number of characters to write
Returns:
the number of items successfully read or written not the number of characters
References CSTR_STR, and cstrDumpN().
Referenced by cstrDumpN().
int cstrEquals (cstr_t str1, cstr_t str2)
String comparison.
This function compares the strings stored at str1 and str2
Parameters:
str1 cstr_t instance
str2 cstr_t instance
Returns:
1 if the strings are equal. 0 otherwise
References CSTR_STR, and cstrEquals().
Referenced by cstrEquals(), and cstrIsClone().
int cstrEqualsI (cstr_t str1, cstr_t str2)
String comparison (case insensitive).
This function compares the strings stored at str1 and str2 but ignores the case
Parameters:
str1 cstr_t instance
str2 cstr_t instance
Returns:
1 if the strings are equal (modulo case). 0 otherwise
References CSTR_LEN, CSTR_STR, and cstrEqualsI().
Referenced by cstrEqualsI().
const char* cstrGetChar (cstr_t str)
Get a pointer to the string.
This function just calls the CSTR_STR() macro, which gives the pointer to the string It returns a const char * because you should only alter the string using the cstr functions
Parameters:
str cstr_t instance
Returns:
a pointer to the string
References CSTR_STR, and cstrGetChar().
Referenced by cstrGetChar().
int cstrGetSubstring (cstr_t dst, cstr_t str, unsigned long int a, unsigned long int b)
Get a substring.
This function extracts a substring from str and places it in dst
Parameters:
dst cstr_t instance which will hold the result
str cstr_t instance from which the substring will be extracted
a left bound
b right bound
Returns:
0 or 1 if if fails ou succeeds, respectively
References CSTR_LEN, CSTR_STR, and cstrGetSubstring().
Referenced by cstrGetSubstring(), cstrLeft(), and cstrRight().
void cstrImport (cstr_t str, FILE * fp)
Import from file.
This function reads the contents of fp (until EOF) and puts it in str
Parameters:
str cstr_t instance
fp input source
References CSTR_INIT_SIZE, cstrConcatInPlaceChar(), cstrImport(), and cstrUpdate().
Referenced by cstrImport().
void cstrImportCharN (cstr_t str, const char * buffer, unsigned long int n)
Read n characters from a byte sequence.
This function reads n characters (bytes) from buffer and places them in str
Parameters:
str cstr_t instance
buffer input source
n number of characters to read
References CSTR_LEN, CSTR_STR, and cstrImportCharN().
Referenced by cstrImportCharN().
void cstrImportN (cstr_t str, FILE * fp, unsigned long int n)
Read n characters from file.
This function reads the first n characters from fp and places them in str
Parameters:
str cstr_t instance
fp input source
n number of characters to read
References CSTR_INIT_SIZE, cstrConcatInPlaceChar(), cstrImportN(), cstrLeft(), cstrLength(), and cstrUpdate().
Referenced by cstrImportN().
unsigned long int cstrIndexOf (cstr_t str, char c)
Get the (first) index of a character.
This function returns the index of the first occurence (left to right) of the character c in the stored string
Parameters:
str cstr_t instance
c the char
Returns:
the index of the first occurence of c or EOF
References CSTR_LEN, CSTR_STR, and cstrIndexOf().
Referenced by cstrIndexOf().
cstr_t cstrInit (void)
Create a cstr_t instance.
Create a cstr_t instance with the default maximum string length (64 chars) This value will be reajusted when needed
Returns:
cstr_t instance
References CSTR_INIT_SIZE, cstrInit(), and cstrInit2().
Referenced by cstrInit().
cstr_t cstrInit2 (unsigned long int n)
Create a cstr_t instance defining the buffer size.
Create a cstr_t instance defining an initial maximum string length This is only the initial maximum. This value will be reajusted when needed
Parameters:
n minimum string size (will be rounded to the next power of 2)
Returns:
cstr_t instance
References CSTR_LEN, CSTR_SIZE, CSTR_STR, cstrInit2(), and powerup().
Referenced by cstrInit(), cstrInit2(), and cstrInitChar().
cstr_t cstrInitChar (char * s)
Create and initialize a cstr_t instance.
Create a cstr_t instance and initialize it with a C string (char *) The buffer size will be powerup(strlen(s))
Parameters:
s string to initialize the cstr_t instance with
Returns:
cstr_t instance
References cstrInit2(), cstrInitChar(), and cstrUpdate().
Referenced by cstrInitChar().
int cstrIsClone (cstr_t str1, cstr_t str2)
cstr instance comparison
This function compares two cstr instances
It returns true if both objects are exactly the same: equal strings and equal buffer size
Parameters:
str1 cstr_t instance
str2 cstr_t instance
Returns:
1 if the objects are equal. 0 otherwise
References CSTR_LEN, CSTR_SIZE, cstrEquals(), and cstrIsClone().
Referenced by cstrIsClone().
unsigned long int cstrLastIndexOf (cstr_t str, char c)
Get the (last) index of a character.
This function returns the index of the last occurence (first, if read right to left) of the character c in the stored string
Parameters:
str cstr_t instance
c the char
Returns:
the index of the last occurence of c or EOF
References CSTR_LEN, CSTR_STR, and cstrLastIndexOf().
Referenced by cstrLastIndexOf().
int cstrLeft (cstr_t dst, cstr_t str, unsigned long int i)
Get a substring starting at the beginning.
This function extracts a substring from str and places it in dst
Parameters:
dst cstr_t instance which will hold the result
str cstr_t instance from which the substring will be extracted
i the size of the substring
Returns:
0 or 1 if if fails ou succeeds, respectively
References cstrGetSubstring(), and cstrLeft().
Referenced by cstrImportN(), and cstrLeft().
unsigned long int cstrLength (cstr_t str)
Get string length.
This function just calls the CSTR_LEN() macro. It is the same as strlen(cstrlibGetChar(str))
Parameters:
str cstr_t instance
Returns:
the length of the string (number of characters, without \0)
References CSTR_LEN, and cstrLength().
Referenced by cstrImportN(), and cstrLength().
void cstrLower (cstr_t str)
Make the string lowercase.
Parameters:
str cstr_t instance
References cstrLower().
Referenced by cstrLower().
void cstrMakeSingleSpace (cstr_t str)
Remove extra space.
This function replaces sequences of white space with a single space. For example, "a b c d" is transformed into "a b c d"
Parameters:
str cstr_t instance
References CSTR_LEN, CSTR_STR, and cstrMakeSingleSpace().
Referenced by cstrMakeSingleSpace().
int cstrReplace (cstr_t str, const char * s1, const char * s2)
Replace a substring with another.
This function searches for the first occurence of s1 in the string stored at str and replaces it with s2
The buffer size will be increased if necessary
Parameters:
str cstr_t instance
s1 the substring to find
s2 the substring which will replace s1
Returns:
1 or 0 if it succeeds or fails, respectively
References cstrReplace().
Referenced by cstrReplace().
unsigned long int cstrReplaceAll (cstr_t str, const char * s1, const char * s2)
Replace all occurences of a substring with another.
This function searches for all the occurences of s1 in the string stored at str and replaces them with s2
The buffer size will be increased if necessary
Parameters:
str cstr_t instance
s1 the substring to find
s2 the substring which will replace s1
Returns:
the number of replaced substrings
References CSTR_LEN, CSTR_NICE_FREE, CSTR_STR, and cstrReplaceAll().
Referenced by cstrReplaceAll().
void cstrResize (cstr_t str)
Re-calculate minimum buffer size.
This function re-calculates the minimum buffer size that is needed to keep the current string. If it is less than the currently allocated, the extra memory will be freed
This is the only way to make the buffer smaller. All the other functions will only increase its size when needed
Parameters:
str cstr_t instance to be resized
References CSTR_LEN, CSTR_SIZE, CSTR_STR, cstrResize(), and powerup().
Referenced by cstrResize().
void cstrReverse (cstr_t str)
String reverse.
This function reverses the string stored in str. For example, "abc" is changed to "cba".
Parameters:
str cstr_t instance
References CSTR_LEN, CSTR_STR, and cstrReverse().
Referenced by cstrReverse().
int cstrRight (cstr_t dst, cstr_t str, unsigned long int i)
Get a substring starting at the end.
This function extracts a substring from str and places it in dst
Parameters:
dst cstr_t instance which will hold the result
str cstr_t instance from which the substring will be extracted
i the size of the substring
Returns:
0 or 1 if if fails ou succeeds, respectively
References CSTR_LEN, cstrGetSubstring(), and cstrRight().
Referenced by cstrRight().
unsigned long int cstrSearch (cstr_t str, char * s)
Search for a substring.
This function searches for the first occurence of s in the string stored at str
Currently uses the KMP algorithm
Parameters:
str cstr_t instance
s the substring to find
Returns:
the index of str where the match occured or CSTR_LEN(str) if s was not found
References CSTR_LEN, CSTR_NICE_FREE, CSTR_STR, and cstrSearch().
Referenced by cstrSearch().
unsigned long int cstrSize (cstr_t str)
Get buffer size.
This function just calls the CSTR_SIZE() macro, which gives the ammount of currently allocated memory. In other words, it returns the length of the biggest string that is possible to store in str
Parameters:
str cstr_t instance
Returns:
the size of the currently allocated string buffer
References CSTR_SIZE, and cstrSize().
Referenced by cstrSize().
void cstrStrip (cstr_t str)
Remove white space from both the beginning and the end of the string.
Parameters:
str cstr_t instance
References cstrStrip(), cstrStripL(), and cstrStripR().
Referenced by cstrStrip().
void cstrStripL (cstr_t str)
Remove white space from the beginning of the string.
Parameters:
str cstr_t instance
References CSTR_LEN, CSTR_STR, and cstrStripL().
Referenced by cstrStrip(), and cstrStripL().
void cstrStripR (cstr_t str)
Remove white space from the end of the string.
Parameters:
str cstr_t instance
References CSTR_LEN, CSTR_STR, and cstrStripR().
Referenced by cstrStrip(), and cstrStripR().
void cstrSwapCase (cstr_t str)
Switch upper with lower case and vice-versa.
This function replaces every lower case character with the correspondent upper case and vice-versa
Parameters:
str cstr_t instance
References cstrSwapCase().
Referenced by cstrSwapCase().
int cstrUpdate (cstr_t str, const char * s)
Store a new string in a cstr instance.
This function stores the string s in the cstr instance
The buffer will not be resized. If needed, it will be increased, but to make smaller (thus freeing some memory) you must call cstrResize()
Parameters:
str cstr_t instance to store a new string
s char array to be stored in str
Returns:
0 or 1 if it fails or succeeds, respectively
References CSTR_LEN, CSTR_SIZE, CSTR_STR, and cstrUpdate().
Referenced by cstrCopy(), cstrImport(), cstrImportN(), cstrInitChar(), cstrUpdate(), and cstrUpdateFormat().
int cstrUpdateFormat (cstr_t str, char * fmt, ...)
Store a new string in a cstr instance according to a format.
This function stores a new string in the cstr instance according to a format. The format specifiers are the following:
%s - a C null terminated string
%d - a C int
%A - a cstr_t instance
An example: suppose you want to create the string "select * from t where u='x' and p='y'". Both values x and y are strings. You have one as a cstr_t instance, a1, and the other as a C null terminated string, s1. The following code will do it:
cstrUpdate(str1, "select * from t where u='%A' and p='%s'", a1, s1);
Parameters:
str cstr_t instance to store a new string
fmt the format string
... the remainder arguments, in the same order as they appear in fmt
Returns:
0 or 1 if it fails or succeeds, respectively
References CSTR_LEN, CSTR_STR, cstrConcatInPlace(), cstrConcatInPlaceChar(), cstrUpdate(), and cstrUpdateFormat().
Referenced by cstrUpdateFormat().
void cstrUpper (cstr_t str)
Make the string uppercase.
Parameters:
str cstr_t instance
References cstrUpper().
Referenced by cstrUpper().
unsigned long int powerup (unsigned long int n)
Get the next power of 2.
This function computes the smallest k, such that k is a power of 2 and k > n
If n is already a power of two, it returns 2*n
Parameters:
n integer (not a power of two)
Returns:
smallest power of 2 greater than n
References powerup().
Referenced by cstrInit2(), cstrResize(), and powerup().